version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: okey_solver_backend
    expose:
      - "8000"
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    networks:
      - okey_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: okey_solver_frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - okey_network

networks:
  okey_network:
    driver: bridge
